### ISSUE TITLE
Typecheck test not working for python version lower or equal to 3.5

### ISSUE THREAD

**Issue by gusmith** [data61/clkhash#282]
Returned error on Windows, python 3.5
```
Collecting mypy
  Downloading https://files.pythonhosted.org/packages/fe/d4/c167320c5831de26e14835b3fe2420915ac0a1efe48f8351f0a1085ec422/mypy-0.720-cp35-cp35m-win_amd64.whl (6.1MB)
Requirement already satisfied, skipping upgrade: mypy-extensions<0.5.0,>=0.4.0 in c:\hostedtoolcache\windows\python\3.5.4\x64\lib\site-packages (from mypy) (0.4.1)
Collecting typing-extensions>=3.7.4 (from mypy)
  Downloading https://files.pythonhosted.org/packages/27/aa/bd1442cfb0224da1b671ab334d3b0a4302e4161ea916e28904ff9618d471/typing_extensions-3.7.4-py3-none-any.whl
Collecting typed-ast<1.5.0,>=1.4.0 (from mypy)
  Downloading https://files.pythonhosted.org/packages/c1/1f/33ea7a3fecec1878e7697ca6bb0e624970f8c3cd8b8932ff6ed74b10858b/typed_ast-1.4.0-cp35-cp35m-win_amd64.whl (155kB)
Installing collected packages: typing-extensions, typed-ast, mypy
Successfully installed mypy-0.720 typed-ast-1.4.0 typing-extensions-3.7.4
clkhash\bloomfilter.py:21: error: Module 'hashlib' has no attribute 'blake2b
```
And `mypy` cannot be installed for python 2.7 (min version of 3.5).

**Comment by hardbyte** [comment]
We don't need to run the `mypy` tool using different versions of python. I'd suggest just using the current stable release e.g. `Python 3.7`

**Comment by hardbyte** [comment]
Also the code in question in `bloomfilter.py` clearly deals with this:

```
try:
    from hashlib import blake2b
except ImportError:
    # We are in Python older than 3.6.
    from pyblake2 import blake2b  # type: ignore
    # Ignore because otherwise Mypy raises errors, thinking that
    # blake2b is already defined.
```

**Comment by gusmith** [comment]
The error provided above was observed in the build https://dev.azure.com/data61/Anonlink/_build/results?buildId=179 on both builds using python 3.5... so I'm not sure what is happening, but it is not supposed to run for Python 3.5, should we just close the issue? Or should we document this somewhere?

**Comment by gusmith** [comment]
We are now only running mypy for python 3.7 for which there is no problem. @hardbyte Should we keep it open?
